basic indexing and slicing [start:end:step]] start to end-1
numeric indexing

In [5]:
import numpy as np

x=np.array([10,20,30,40,50,60,70])

print(x)

print(type(x))

#l=[1,2,5]

#print(x[-6:-2:2])

#print(x[[1,4,5]])

cond = x > 40

print(type(cond))

print(cond)

print(x[cond])

print(type(x[cond]))

print(x[x>40])






[10 20 30 40 50 60 70]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[False False False False  True  True  True]
[50 60 70]
<class 'numpy.ndarray'>
[50 60 70]


In [6]:
y = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(y.ndim)

print(y.shape)

print(y)

# print(y[0][1])

# print(y[0,1])

# print(y[:2,:2])

# print(y[[0,2],[0,1]])

print(y[y>30])




2
(3, 3)
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[40 50 60 70 80 90]


where()

ter = x if cond else y

In [9]:
print(y)

arr= np.where(y>30, 1, 0)

print(arr)

arr1= np.where(y>30, y, 0)

print(arr1)



[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[0 0 0]
 [1 1 1]
 [1 1 1]]


In [22]:
z=np.array([[10,20],[30,40],[np.nan,50]])

print(z)

print(type(z))

s=np.isnan(z)

print(s)

print(z[s])

[[10. 20.]
 [30. 40.]
 [nan 50.]]
<class 'numpy.ndarray'>
[[False False]
 [False False]
 [ True False]]
[nan]
