Starting with Numpy

Methods to create numpy array/nd array

In [2]:
import numpy

arr = numpy.array([3,4,5])

print(arr)

print(type(arr))

print(arr.ndim)#axes 0 -1st dimen, 1- 2nd dimen

print(arr.shape)

[3 4 5]
<class 'numpy.ndarray'>
1
(3,)


In [3]:
import numpy as np

arr = np.array([[1,2,3],[4,5,600000000000]])

print(arr)

print(type(arr))

print(arr.ndim)#axes 0 -1st dimen, 1- 2nd dimen

print(arr.shape)

print(arr.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
int32
